version: "3.8"
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_ASR_MODEL=whisper-1
      - OPENAI_LLM_MODEL=gpt-4o-mini
    volumes:
      - ./backend/storage:/app/storage
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE=http://localhost:8000
